### ISSUE TITLE
HELP: Алгоритм Сборки

### ISSUE THREAD

**Issue by diper1998** [allnes/MPI_Practical_Course#12]
Сейчас я напишу, что я делаю. И если я где-то неправильно делаю, то поправьте, ибо я не знаю, что я делаю.
1 шаг:  
создать папку Perov_Dima_task1_SumElVect : 
D:\GitHubDesktop\MPI_Practical_Course\build\modules\task_1\Perov_Dima_task1_SumElVect 
В неё засовываем main.cpp и CMakeList, 
в котором изменяем в project(...) на project(Perov_Dima_task1_SumElVect )
Потом засовываем в test_task тоже main.cpp (! без этого cmake выдаст ошибку !)
2 шаг: 
создаем папку build : 
D:\GitHubDesktop\MPI_Practical_Course\build
Переходим туда в командной строке и делаем cmake D:\GitHubDesktop\MPI_Practical_Course

![default](https://user-images.githubusercontent.com/33723506/46545609-71554800-c8cf-11e8-893f-96d6a2d48c6d.PNG)

Получили:

![ccc](https://user-images.githubusercontent.com/33723506/46545675-a1045000-c8cf-11e8-90f1-ab86b9575a4f.PNG)

И так же получили: 
![default](https://user-images.githubusercontent.com/33723506/46545726-c85b1d00-c8cf-11e8-9178-702872cae2a6.PNG)

Дальше нужно сделать msbuild, но вопрос с каким sln сделать msbuild?

3 шаг:
Изменить .travis.yml и appveyor.yml и уже можно пул-реквестить?

**Comment by allnes** [comment]
На шаге 1  - проблемы с test_task у меня не возникали, пробный pull-request прошел и находится в pull-request'ах  как доказательство, если воспроизводится ошибка - пришлите ее сюда в виде фото или описания, я разберусь.
На шаге 2 - строится нужно не в корневой директории проекта, а выше уровнем, либо пропишите   gitignore для папки build. Про gitignore - это файл со списком не учитвающихся объектов, можно  [здесь](https://ru.stackoverflow.com/questions/546520/%D0%94%D0%BB%D1%8F-%D1%87%D0%B5%D0%B3%D0%BE-%D0%BD%D1%83%D0%B6%D0%B5%D0%BD-%D1%84%D0%B0%D0%B9%D0%BB-gitignore) 
Также на шаге 2 нужно строиться c msbuild ALL_BUILD.vcxproj
На шаге 3 - да, нужно изменять конфигурационнын файлы .travis.yml и appveyor.yml

**Comment by diper1998** [comment]
Так, значит строиться нужно вне папки MPI_Practical_Course или создавать папку build к примеру в task_1?

**Comment by allnes** [comment]
Можно вне папки, а можно в корневой папке MPI_Practical_Course под названием build

**Comment by diper1998** [comment]
Вот что получается... Может нужно убрать Cmakelist из test_task?

![11](https://user-images.githubusercontent.com/33723506/46548354-88983380-c8d7-11e8-8e36-c3526ee4b13d.PNG)

![223](https://user-images.githubusercontent.com/33723506/46548356-8a61f700-c8d7-11e8-9ba9-75c2113fbd4a.PNG)

**Comment by diper1998** [comment]
Или нужно в cmakelist в test_task прописать project(Perov_Dima_task1_SumElVect ) вместо project( test_task) ?

**Comment by allnes** [comment]
@diper1998
Соберите исходный проект, который вы форкнули и проверьте, вероятнее всего потерялся main.cpp

**Comment by allnes** [comment]
test_task вам трогать не надо

**Comment by allnes** [comment]
А ещё вы работаете в master, а этого делать не нужно

**Comment by diper1998** [comment]
Я просто удалил из test_task main.cpp файл... Сейчас верну. Немного не понятно то, что мы собираемся вне папки MPI_Practical_Cours... как бы папка с MPI_BUILD нам вообще не нужен будет для того, чтобы сделать пул-реквест? И в файлах .travis.yml и appveyor.yml уже делается cmake и создается свой build...

**Comment by ivanvikhrev** [comment]
@allnes  а важно ли как называется cpp файл?  Если у меня, допустим, вместо main.cpp в ..\task1\  лежит array_sum.cpp и при этом я указал это в CMakeLists.txt.

**Comment by allnes** [comment]
@ivanvikhrev не важно как называется, главное чтобы работало и проходило построение

**Comment by diper1998** [comment]
Тогда чтобы запул-реквестить нужно дописать в .travis.yml
-mpirun -np 4 ./modules/task_1/Perov_Dima_task1_SumElVect/Perov_Dima_task1_SumElVect (2 раза повторяется?)

В appveyor.yml 
- cmd: mpiexec.exe -np 4 modules\task_1\Perov_Dima_task1_SumElVect\%configuration%\Perov_Dima_task1_SumElVect.exe  ?

**Comment by allnes** [comment]
@diper1998 да

**Comment by ivanvikhrev** [comment]
@allnes  нужно ли открывать новый пулл реквест, если внес изменения в проект, или можно переоткрыть старый?

**Comment by diper1998** [comment]
Тааак... а как сделать пулреквест в таком случае? 
![default](https://user-images.githubusercontent.com/33723506/46551959-d74acb00-c8e1-11e8-8afa-e030542db6df.PNG)

**Comment by allnes** [comment]
@ivanvikhrev пулл реквест один, внутри него можно все изменять, переоткройте старый.

**Comment by allnes** [comment]
@diper1998 вы работаете в мастере, а вам нужно работать в своей ветке.
