### ISSUE TITLE
Как правильно исправлять конфликты после принятия нового реквеста? 

### ISSUE THREAD

**Issue by Agricola87** [allnes/MPI_Practical_Course#25]
Как правильно исправлять конфликты после принятия нового реквеста?
Нужно ли клонировать проект заново?

**Comment by allnes** [comment]
@Agricola87  клонировать ничего не нужно.
Используйте команду `git pull --rebase upstream master`, если она выдаст ошибку, то вам придется в ручную поправлять каждый кусок конфликта, какие конфликты - будет показано после вызова этой команды.

**Comment by allnes** [comment]
И файлы для изменения должны быть такие, которые показаны в тестовом пулл реквесте.

**Comment by Agricola87** [comment]
Я исправил
