### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lesya89** [allnes/MPI_Practical_Course#29]
при сборке cmake дает ошибку конфигурации, не найдены библиотеки mpi
 
![2018-10-17 10 29 47](https://user-images.githubusercontent.com/33698001/47069460-387e7280-d1ef-11e8-856e-44b67c390599.png)

**Comment by allnes** [comment]
@lesya89 
1) Проверьте работает ли mpiexec в консоли.
2) Установили ли вы оба пакета msmpisdk.msi и msmpisetup.exe?
3) Если у вас стоит Intel MPI (и постараться полоностью его удалить), то вам надо его заменить на Microsoft MPI.

**Comment by lesya89** [comment]
Пыталась собраться локально,чтоб проверить работает ли, но консоль не видит cmake насколько я понимаю

![2018-10-17 13 58 18](https://user-images.githubusercontent.com/33698001/47082431-ce28fa80-d20d-11e8-8876-7dc26ca6d235.png)

**Comment by allnes** [comment]
@lesya89 
В данном проекте cmake принимает CMakeLists.txt(а не main.cpp), находящийся в корневом каталоге проекта.

**Comment by lesya89** [comment]
нууу
![2018-10-17 14 25 18](https://user-images.githubusercontent.com/33698001/47083518-18f84180-d211-11e8-8853-76571d3ea79c.png)

**Comment by allnes** [comment]
@lesya89 CMakeLists.txt находится в корневом каталоге, т.е. в папке MPI_Practical_Course, а не MPI_Practical_Course/modules/task_1

**Comment by lesya89** [comment]
а как тогда потом собрать мой проект? потому что он собирает тестовый

![2018-10-17 16 39 27](https://user-images.githubusercontent.com/33698001/47090273-e3f4ea80-d222-11e8-87af-51c9445cac01.png)

**Comment by allnes** [comment]
@lesya89 
1) добавьте мой репозиторий в синхронизируемые `git remote add upstream https://github.com/allnes/MPI_Practical_Course`
2) обновите вашу ветку `git pull --rebase upstream master`
3) соберите проект заново и вы увидите, что ваши одногруппники сделали и как собрались в этом же проекте
