### ISSUE TITLE
Ускорение при использовании параллельного метода

### ISSUE THREAD

**Issue by Enreyz** [allnes/MPI_Practical_Course#49]
Я переделал программу, оптимизировав рассылку данных 0-вым процессом(до этого отсылал вектор целиком каждому процессу), но ускорения не добился. Является ли наличие ускорения обязательным фактором правильности работы программы? Я пытался добавлять в программу метки времени, контролируя на что больше всего тратится время работы. Результаты получились следующие: на 2 процессах с вектором размера 1 млн. элементов программа при использовании линейного способа вычисления минимума тратит примерно 0.003 секунды. При использовании параллельного способа вычисления программа затрачивает примерно 0.006-0.007 секунды, при этом 0.003-0.004 уходит на выполнение send'a и recv'а. На последнем pull-request'e trevis и appveyor показали еще более плохие результаты, хоть программа и запускалась на 4 процессах. Я уже не знаю, что мне нужно переделать в своем коде, чтобы был выигрыш во времени при использовании параллельного способа вычисления, как и у остальных ребят. Код считаю правильным.

**Comment by allnes** [comment]
@Enreyz 
1) Вероятнее всего travis и appveyore не рассчитаны для таких вычислений.
2) Я завтра еще проверю на кластере ваши вычисления.
3) Если вы считаете, что у вас все правильно, то в субботу продолжите сдачу.
