### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by lesya89** [allnes/MPI_Practical_Course#50]
У меня на локальной машине не видит ветку, на которой я до этого работала, только master
Если я пытаюсь создать новую, то выдает merge-конфликт

**Comment by allnes** [comment]
Если у вас образовалась ошибка с гитом, можно удалить эту директорию и клонировать заново.

**Comment by lesya89** [comment]
Я пробовала

**Comment by lesya89** [comment]
Я в попытках сознания нового pull request, чтоб измененую версию залить
