### ISSUE TITLE
Сдача 1 задачи

### ISSUE THREAD

**Issue by Pahandrovich** [allnes/MPI_Practical_Course#57]
Я сегодня весь день менял код, смотрел что получится. В итоге переписал программу с функциями MPI_Scatter и MPI_Reduce, результаты получились еще хуже. Посмотрел программы одногруппников, увидел, что алгоритм решения с send/recv качественно один и тот же и я не понимаю, почему нет выигрыша во времени. Я замерил время выполнения кусков работы программы на отсылке данных (MPI_Send), на участке вычисления своей части 0-м процессом и на участке приёмки 0-м процессом результатов остальных процессов. Увидел, что два MPI_Send убивают времени примерно столько же, сколько и линейный подсчет, а если прибавить к этому времени, хоть и незначительное, но время счета и приёмки,то отсюда и вытекает проигрыш. В программе с функциями Scatter/Reduce, две подряд вызываемые функции MPI_Scatter также замедляют программу на время, большее чем время линейного вычисления.
Я не знаю как её оптимизировать или переписать так, чтобы был прирост производительности.

**Comment by allnes** [comment]
@Pahandrovich я переписал вашу задачу с 0, она  [здесь](https://github.com/allnes/MPI_Practical_Course/pull/58).
Результаты работы на кластере [здесь](https://drive.google.com/file/d/1ZjHRVPruILq9ItDVO338KahM6M38hcb7/view?usp=sharing).
Увы, но за решение я ставлю 0.

**Comment by Pahandrovich** [comment]
Я посмотрел Вашу программу. Когда я писал свою программу с Scatter/Reduce, она была написана по сути также, но прироста не было. И Ваша программа у меня на компьютере тоже не даёт выигрыша по времени.
![image](https://user-images.githubusercontent.com/35104773/47969112-e0b38880-e083-11e8-9119-a6ab38bf82e4.png)

**Comment by Pahandrovich** [comment]
это не может быть из-за того, что для выполнения одной итерации подсчета скалярного произведения требуется два разных элемента. Отправлял бы я один вектор, выигрыш был бы очевиден.

**Comment by Pahandrovich** [comment]
С 0-м баллов я смирюсь, но мне хочется разобраться в этом, чтобы не допускать ошибок в следующих программах

**Comment by allnes** [comment]
@Pahandrovich вы присылали сюда pull-request с версиями scatter/reduce, а то я не нахожу ее. Охото взглянуть еще раз. И я не совсем понял формулировку предпоследнего комментария.

**Comment by Pahandrovich** [comment]
Про первую версию согласен) Там не подумал насчёт 0-го процесса.

**Comment by Pahandrovich** [comment]
Просто мне кажется эту задачу нельзя сделать с ускорением, т.к. на каждой итерации требуется по одному элементу из 2-х векторов. Тогда в отправке был бы один Send, отсылающий в общей сложности 3\4*n элементов памяти (для 4-х процессов). Соответственно время, потраченное на отправку было бы в 2 раза меньше и прирост наблюдался бы.
А тут, так как вектора 2, значит объём отсылаемой памяти 2*(3/4)*n, и времени тратится в 2 раза больше.

**Comment by allnes** [comment]
@Pahandrovich да эти рассуждения правильные, при условии что отсылки не были бы асинхронными, но это не так. Я проверил ваш пулл-реквест на 32 процессах на кластере, чтобы избежать проблем с малой мощностью и вот что я получил [опять](https://drive.google.com/open?id=1ovIiksdP6PVW1ulhrC23NXiW9PNglPjd). Сейчас в самом пулл-реквесте опишу в комментариях проблему. Версии моей и вашей программы практически схожи, но есть одна разность которая сильно изменяет работу.

**Comment by Pahandrovich** [comment]
то есть количество элементов, отправляемых каждому процессу лучше делать с округлением в большую сторону (ceil), чтобы в векторах не оставалось "лишних" элементов при отправке?

**Comment by allnes** [comment]
@Pahandrovich да, те самым процесс не будет работать в холостую

**Comment by Pahandrovich** [comment]
Вроде понял.
Думаю в версии с send/recv была аналогичная недоработка)
Спасибо, что потратили время)
