### ISSUE TITLE
Сроки выполнения. 

### ISSUE THREAD

**Issue by lesya89** [allnes/MPI_Practical_Course#6]
За какое время нам нужно сдать первую задачку?

**Comment by allnes** [comment]
@lesya89 , я написал Александру Владимировичу, ждем ответа.
Как только я узнаю, то сразу эта информация появится в таблице результатов сдачи.
Следите за информацией.

**Comment by allnes** [comment]
@lesya89  , информация обновилась, красная краница сдачи перовй лабораторной работы будет вероятнее всего 20 октября. Поэтому ставим пока 20 октября до следующего обновления.
