### ISSUE TITLE
Вторая лабораторная работа.

### ISSUE THREAD

**Issue by morphine43** [allnes/MPI_Practical_Course#60]
Добрый вечер, в примерно таком виде пойдёт?
Просто это оказалось несколько сложнее, чем я думал, возможно связано с реализацией.
![topologies_test](https://user-images.githubusercontent.com/37037117/48074420-efb84900-e1f1-11e8-801a-fff50bd909ad.PNG)

**Comment by morphine43** [comment]
Я пока что сделал наброски для ринга только, но вроде работает.

**Comment by allnes** [comment]
@morphine43 объясните сначала, как интерпретировать данные в консоли.

**Comment by morphine43** [comment]
Generate это source процесс создаёт пакет.
Дальше происходит отправка.
Т.к. отправить пакет от 2 к 0 "дешевле", чем от 2 к 1, а от 1 к 0, то он отправляет так.
Так мы можем отправить потому что это топология кольцо 
![ring_topology](https://user-images.githubusercontent.com/37037117/48075794-0613d400-e1f5-11e8-9427-ef34f36882c2.png)
(в названии line, но я решил сначала сделать ring).

**Comment by allnes** [comment]
@morphine43 все нормально, только воспроизведите в этой топлогии какой-либо алгоритм (например произведение матриц), иначе я никак не првоерю работоспособность.
