### ISSUE TITLE
Не собирается проект

### ISSUE THREAD

**Issue by ivanvikhrev** [allnes/MPI_Practical_Course#68]
Здравствуйте.
Пытаюсь собрать проект сmake`ом и он выдает not build:
![image](https://user-images.githubusercontent.com/32363146/48567336-757c7880-e905-11e8-8745-eab5d54dd49e.png).
Переменные окружения openCV установил.
файл CmakeLists.txt:
https://github.com/ivanvikhrev/MPI_Practical_Course/blob/Vikhrev_task2/modules/task_2/Vikhrev_Ivan_task2_ImageProcessing/CMakeLists.txt

**Comment by ivanvikhrev** [comment]
Там надо if( UNIX ) убрать?

**Comment by allnes** [comment]
@ivanvikhrev посмотрите как сделано в тестовом пуллреквесте при сборке
