### ISSUE TITLE
make

### ISSUE THREAD

**Issue by Agricola87** [allnes/MPI_Practical_Course#7]
По туториалу, после того, как cmake отработало, надо ввести в консоль make, но такой команды консоль не принимает. Надо ли еще что-то устанавливать или в Windows нужна другая команда?

**Comment by allnes** [comment]
@Agricola87 , для Linux это make, для Windows это msbuild. Вы используете make с Windows, что нет в консоли Visual Studio.

**Comment by Agricola87** [comment]
Спасибо!
