### ISSUE TITLE
Задача №2. Размер данных для запуска на кластере.

### ISSUE THREAD

**Issue by IvanYunin** [allnes/MPI_Practical_Course#82]
Задача была запущена на кластере с исходными данными 20000 20000 так как на больших данных задача не запускается? 
Может ли быть такое что пересылка начинает забирать большее количество времени, при большом количестве данных?

**Comment by allnes** [comment]
@IvanYunin 
1) Я прогонял с интервалом 1000, на 20000 я уже долго ждал работы программы, но ускорения так и не получил, все было линейно, хотя такого быть не должно.
2) Да, такое может быть, при неправильной схеме распараллеливания.

**Comment by IvanYunin** [comment]
@allnes 
Для кластера можно не достигать времени работы программы в несколько секунд?

**Comment by allnes** [comment]
это и странно

**Comment by allnes** [comment]
все говорит о том что с кодом что-то не то

**Comment by IvanYunin** [comment]
Спасибо за ответы. Буду править.
