### ISSUE TITLE
Вопрос по задаче 3.

### ISSUE THREAD

**Issue by Agricola87** [allnes/MPI_Practical_Course#86]
Вычисление многомерных интегралов методом Монте-Карло.
1. Функцию от какого количества переменных нужно интеггрировать. Это не может задаваться с консоли, т.к. сама функция задается в коде явно.
2. Как нужно проверять результат? Вариант 1 (на мой взгляд, правильный): для малых N (до 20, например, если N=3, вычислять с одновременным использованием метода Римана, выводить погрешность и сообщать о удовлетворении некоторой точности, а далее считать, что алгоритм корректный и выводить только результат метода Монте-Карло. Вариант 2: считать аналитически и сравнивать. Недостаток: нельзя тестировать на разных функциях, т.к. аналитичское выражение для интеграла надо пересчитывать каждый раз.
3. За границы интегрирования предлагаю взять многомерный куб со стороной [0,1].
4. Взять за функцию что-то вроде f(x)= sin(x+y)z + z^2x +1.

**Comment by Agricola87** [comment]
Передумал. Наоборот, метод Римана сам по себе дает порядочное отклонение. Лучше просто взять какую-то функцию и подсчитать определенный интеграл. Это гораздо убедительнее.

**Comment by allnes** [comment]
@Agricola87 
1) 3-х переменных будет достаточно
2) Возьмите аналитическое решение, пусть функцию будет фиусированной (попробуйте неберущиеся интегралы еще, для инх есть таблицы значений)
3) Границы интегрирования вводить в консоли (в пределах области определения функции)
4) Не берите тривиальную функцию

**Comment by allnes** [comment]
1) тогда без нерерущихся
2) да, методом Римана тогда (главное не оишибиться)
3) можете в файл написать 6 границ и считывать с файла

**Comment by Agricola87** [comment]
Понял
