### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by diper1998** [allnes/MPI_Practical_Course#9]
Здравствуйте! При выполнении cmake пишет: 
-- Could NOT find MPI_C (missing: MPI_C_WORKS)
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
MPI устанавливал... Да и до этого был MPI от Intel с Parallel Studio.
Что делать? Помогите...
![default](https://user-images.githubusercontent.com/33723506/46393243-064c1b80-c6ed-11e8-952e-164c34b600c5.PNG)

**Comment by allnes** [comment]
Добрый день!
Вероятнее всего у Вас сбились пути в переменных окружения, поэтому попробуйте указать пути до самих исходников MPI в ручную:
`cmake -D MPI_INCLUDE_PATH=<путь до заголовочных файлов MPI>
 -D MPI_LIBRARIES=<путь до библиотек >`
